version: "3"
services:
  nginx:
    ports:
      - "80:80"

  programmer-server:
    build:
      context: .
      args:
        - NODE_ENV=prod
    env_file:
      - ./.env

  mongo:
    env_file:
      - ./.env2