version: "3"
services:
  programmer-server:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    env_file:
      - ./.env

  mongo:
    image: mongo
    volumes:
      - my-mongo:/data/db
    ports:
      - "27017:27017"

volumes:
  my-mongo:
