version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  programmer-server:
    build: .
    depends_on:
      - mongo
    env_file:
      - ./.env

  mongo:
    image: mongo
    volumes:
      - my-mongo:/data/db
    ports:
      - "27017:27017"

volumes:
  my-mongo:
