---
- name: Install Docker
  apt:
    name: docker.io
- name: Install Docker Compose
  ansible.builtin.shell: sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- name: Give executable permissions
  ansible.builtin.shell: sudo chmod +x /usr/local/bin/docker-compose
- name: Add current user to docker group
  ansible.builtin.shell: sudo usermod -aG docker $USER
- name: Start the docker service
  service:
    name: docker
    enabled: true
    state: started